version: '3'
services:
  db:
    container_name: postgres
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  reviews-api:
    container_name: reviews-api
    image: reviews-api:1.1
    restart: always
    ports:
      - '8000:80'
volumes:
  postgres: